apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
spec:
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      containers:
        - name: metabase
          image: metabase/metabase:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: metabase-config
          volumeMounts:
            - name: metabase-data
              mountPath: /metabase-data
      volumes:
        - name: metabase-data
          persistentVolumeClaim:
            claimName: metabase-pvc
