apiVersion: v1
kind: ConfigMap
metadata:
  name: metabase-config
data:
  MB_DB_TYPE: postgres
  MB_DB_DBNAME: metabase
  MB_DB_PORT: '5432'
  MB_DB_USER: admin
  MB_DB_PASS: metabasetest
  # host name configured for DB deployed to namespace "metabase" with service name "postgres"
  MB_DB_HOST: postgres.metabase
