apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metabase
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: ./metabase
    repoURL: https://github.com/guo-codefresh/metabase.git
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: metabase
  syncPolicy:
    # this app is configured to sync automatically
    # you must disable autosync if also using the included CF pipeline
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
