# For simplicity, this example uses hostPath node local storage
# For a real deployment, it is recommended to use an
# external volume available to your platform for your PV
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  labels:
    type: local  
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi 
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/postgres"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc  
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany  
  resources:
    requests:
      storage: 5Gi  
